#!/usr/bin/env python3

import sys

from rqt_ros1_example.rqt_ros1_example import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_ros1_example.rqt_ros1_example.MyPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
